export default {
  badgeText: {
    color: '#fff',
  },
  circulSector: {
    // margin: 2,
    // justifyContent: 'center',
    // alignItems: 'center',
    height: 27,
    width: 27,
  },
  textcirculSector: {
    color: '#fff',
    fontSize: 12,
    padding: 0,
  },
  segmentsFilters: {
    paddingTop: 10,
    borderRadius: 10,
    overflow: 'hidden',
    width: '100%',
  },
  btnSegmen: {},
  formFilterHome: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchBarH: {
    borderColor: '#7e7e7d',
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 5,
    paddingRight: 5,
    flex: 6,
  },
  searchBarHIcon: {
    color: '#7e7e7d',
    fontSize: 20,
    marginRight: 5,
  },
  btnBoxFilter: {
    marginLeft: 10,
    flex: 1,
  },
  btnFilter: {
    borderRadius: 10,
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconFilterH: {
    marginLeft: 0,
    marginRight: 0,
  },
  textBtnSegmen: {
    textTransform: 'capitalize',
    fontSize: 16,
    paddingLeft: 20,
    paddingRight: 20,
  },
  btnSegmenFirstHome: {
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    borderLeftColor: '#D80212',
    borderTopColor: '#D80212',
    borderBottomColor: '#D80212',
  },
  btnSegmenLastHome: {
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
  formFilterHomeView: {
    padding: 10,
  },
  formFilterHomeItem: {},
  formFilterHomeBtn: {},
  modalLeyendaV: {
    marginBottom: 50,
    marginLeft: 16,
    marginTop: 50,
    marginRight: 16,
    width: '90%',
    borderRadius: 10,
    backgroundColor: 'white',
    height: 'auto',
    flex: 1,
    justifyContent: 'center',
    padding: 25,
    paddingBottom: 5,
  },
}
