import { StyleSheet } from 'react-native'
import Theme from 'themes/default'

export default StyleSheet.create({
  badgeText: {
    color: '#fff',
  },
  circulSector: {
    height: 27,
    width: 27,
  },
  textcirculSector: {
    color: '#fff',
    fontSize: 12,
    padding: 0,
  },
  segmentsFilters: {
    paddingTop: 10,
    borderRadius: 10,
    overflow: 'hidden',
    width: '100%',
  },
  formFilterHome: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchBarHIcon: {
    color: Theme.COLORS.PRIMARY,
    fontSize: 20,
    marginRight: 5,
  },
  btnBoxFilter: {
    marginLeft: 10,
    flex: 1,
  },
  btnFilter: {
    borderRadius: 10,
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBtnSegmen: {
    textTransform: 'capitalize',
    fontSize: 16,
    paddingLeft: 20,
    paddingRight: 20,
  },
  formFilterHomeView: {
    padding: 10,
  },
  formFilterHomeItem: {},
  formFilterHomeBtn: {},
  modalLeyendaV: {
    marginBottom: 50,
    marginLeft: 16,
    marginTop: 50,
    marginRight: 16,
    width: '90%',
    borderRadius: 10,
    backgroundColor: 'white',
    height: 'auto',
    flex: 1,
    justifyContent: 'center',
    padding: 25,
    paddingBottom: 5,
  },
  /* from estilos */
  modalLeyenda: {},
  modalLeyendaBox: {
    // marginBottom: 35,
    // marginTop: 10,
    // marginLeft: 16,
    // marginRight: 16,
    // height: '100%',
    // maxWidth: '100%',
    // borderRadius: 10,
    // backgroundColor: 'white',
    // flex: 1,
    // justifyContent: 'center',
    padding: 25,
    // paddingTop: 20,
    // paddingBottom: 5,
  },
  // LeyendaTitel: {
  //   color: Theme.COLORS.BLACK,
  //   fontSize: 24,
  //   fontWeight: 'bold',
  // },
  // leyendaText: {
  //   color: Theme.COLORS.BLACK,
  //   fontSize: 16,
  // },
  leyendaSector: {
    marginLeft: 0,
    alignItems: 'center',
    borderBottomWidth: 0,
    borderBottomColor: undefined,
    marginBottom: 0,
    marginTop: 0,
    paddingBottom: 0,
    paddingTop: 5,
    paddingLeft: 0,
  },
  circulLeyenda: {
    margin: 4,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: 40,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 5,
    borderRadius: 30,
  },
  textcirculLeyenda: {
    fontSize: 24,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  listItem: {
    // borderBottomWidth: 0,
    // borderBottomColor: undefined,
    // marginLeft: 0,
    // paddingBottom: 4,
    // paddingTop: 4,
    // paddingVertical: 4,
  },
  itemBodyFicha: {},
  itemTitle: {
    color: Theme.COLORS.PRIMARY,
    marginLeft: 0,
    fontWeight: 'bold',
    paddingBottom: 10,
    marginTop: 16,
  },
  dateFicha: {
    color: Theme.COLORS.BLACK,
    fontSize: 16,
    // fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  textItem: {
    fontSize: 18,
  },
  masFiltrosBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Theme.SIZES.BASE,
  },
  masFiltrosBtnText: {
    color: Theme.COLORS.PRIMARY,
    fontWeight: 'bold',
    textTransform: 'capitalize',
    fontSize: 18,
  },
  searchBarH: {
    borderColor: Theme.COLORS.BLACK,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: 0,
    flex: 6,
  },
  filtrarBtn: {
    marginTop: 45,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  borderBtn: {
    borderRadius: 8,
  },
  filtrarBtnText: {
    textTransform: 'capitalize',
    fontSize: 18,
    fontWeight: 'bold',
  },
  textItemFicha: {},
  tittleFicha: {
    color: Theme.COLORS.PRIMARY,
    marginLeft: 0,
    fontWeight: 'bold',
    paddingBottom: 15,
  },
  btnPicker: {
    borderColor: Theme.COLORS.BLACK,
    height: 35,
  },
  btnListFicha: {
    textTransform: 'capitalize',
    paddingLeft: 10,
    paddingRight: 10,
  },
  dateBtnListFichaSectores: {},
  iconFilterH: {
    marginLeft: 13,
    marginRight: 13,
    fontSize: 26,
  },
  mTop: {
    marginTop: 14,
  },
})
